// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app.contact', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/contact', {
        templateUrl: 'views/contact/index.html',
        controller: 'contactCtrl'
      });
    }
  ]).controller('contactCtrl', [
    '$scope', '$http', function($scope, $http) {
      return $scope.sendEmail = function() {
        if (!$scope.emailForm.$valid) {
          $('#error').fadeIn();
        } else {
          $http({
            method: 'POST',
            url: 'data/index.php?sendEmail',
            data: JSON.stringify($scope.contact)
          }).success(function(response) {
            if (response.valid === "true" && response.send === "true") {
              $('#error').remove();
              return $('#emailForm').fadeOut(500, function() {
                $('#emailForm').remove();
                $('#success').fadeIn();
                $scope.contact = {};
              });
            }
          }).error(function() {
            alert('Brak połączenia z serwerem - proszę spróbować jeszcze raz');
          });
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=config.js.map
