// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app.aboutMe', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/about-me', {
        templateUrl: 'views/about-me/index.html',
        controller: 'aboutMeCtrl'
      });
    }
  ]).controller('aboutMeCtrl', [
    '$scope', function($scope) {
      return $scope.$on('$viewContentLoaded', function() {});
    }
  ]);

}).call(this);

//# sourceMappingURL=config.js.map
