// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app.skills', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/skills', {
        templateUrl: 'views/skills/index.html',
        controller: 'skillsCtrl'
      });
    }
  ]).controller('skillsCtrl', [
    '$scope', '$http', function($scope, $http) {
      $http({
        url: 'data/index.php?skill-lists'
      }).success(function(response) {
        return $scope.skillsList = response;
      });
      return $http({
        url: 'data/index.php?skill-icons'
      }).success(function(response) {
        return $scope.skillsIcons = response;
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=config.js.map
