// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app').directive('siteNav', function() {
    return {
      controller: 'siteNavCtrl',
      templateUrl: 'directives/site-nav/index.html',
      scope: {},
      link: function(scope, element, attrs) {
        $('#show-site-nav').on('click', function() {
          return $('#main-site-nav').addClass('show');
        });
        return element.on('click', function() {
          return $('#main-site-nav').removeClass('show');
        });
      }
    };
  }).controller('siteNavCtrl', [
    '$scope', '$location', function($scope, $location) {
      $scope.changeView = function(view) {
        return $location.path(view);
      };
      return $scope.isActive = function(viewLocation) {
        return viewLocation === $location.path();
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=config.js.map
