// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app', ['ngRoute', 'ngAnimate', 'ngSanitize', 'angular-perfect-scrollbar-2', 'app.frontPage', 'app.projects', 'app.project', 'app.skills', 'app.canDo', 'app.copyright', 'app.aboutMe', 'app.contact']).config([
    '$locationProvider', '$routeProvider', function($locationProvider, $routeProvider) {
      $locationProvider.hashPrefix('!');
      return $routeProvider.otherwise({
        redirectTo: '/'
      });
    }
  ]).factory('viewStg', function($location) {
    return {
      changeView: function(view) {
        return $location.path(view);
      },
      isActive: function(viewLocation) {
        return viewLocation === $location.path();
      }
    };
  }).run(function($rootScope, viewStg) {
    return $rootScope.view = viewStg;
  });

}).call(this);

//# sourceMappingURL=app.js.map

// Generated by CoffeeScript 1.10.0
(function() {


}).call(this);

//# sourceMappingURL=filters.js.map

// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app').directive('audioPlayer', function() {
    return {
      controller: 'audioPlayerCtrl',
      templateUrl: 'directives/audio-player/index.html',
      scope: {},
      link: function(scope, element, attrs) {
        if (Modernizr.audio) {
          return $.initAudioPlayer();
        } else {
          return $('#audio-next, #audio-play').remove();
        }
      }
    };
  }).controller('audioPlayerCtrl', [
    '$scope', '$location', function($scope, $location) {
      return $scope.changeView = function(view) {
        return $location.path(view);
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=config.js.map

// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app').directive('siteNav', function() {
    return {
      controller: 'siteNavCtrl',
      templateUrl: 'directives/site-nav/index.html',
      scope: {},
      link: function(scope, element, attrs) {
        $('#show-site-nav').on('click', function() {
          return $('#main-site-nav').addClass('show');
        });
        return element.on('click', function() {
          return $('#main-site-nav').removeClass('show');
        });
      }
    };
  }).controller('siteNavCtrl', [
    '$scope', '$location', function($scope, $location) {
      $scope.changeView = function(view) {
        return $location.path(view);
      };
      return $scope.isActive = function(viewLocation) {
        return viewLocation === $location.path();
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=config.js.map

// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app.aboutMe', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/about-me', {
        templateUrl: 'views/about-me/index.html',
        controller: 'aboutMeCtrl'
      });
    }
  ]).controller('aboutMeCtrl', [
    '$scope', function($scope) {
      return $scope.$on('$viewContentLoaded', function() {});
    }
  ]);

}).call(this);

//# sourceMappingURL=config.js.map

// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app.canDo', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/can-do', {
        templateUrl: 'views/can-do/index.html',
        controller: 'canDoCtrl'
      });
    }
  ]).controller('canDoCtrl', [
    '$scope', '$http', function($scope, $http) {
      return $http({
        method: 'GET',
        url: 'data/index.php?offers'
      }).success(function(response) {
        return $scope.offers = response;
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=config.js.map

// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app.contact', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/contact', {
        templateUrl: 'views/contact/index.html',
        controller: 'contactCtrl'
      });
    }
  ]).controller('contactCtrl', [
    '$scope', '$http', function($scope, $http) {
      return $scope.sendEmail = function() {
        if (!$scope.emailForm.$valid) {
          $('#error').fadeIn();
        } else {
          $http({
            method: 'POST',
            url: 'data/index.php?sendEmail',
            data: JSON.stringify($scope.contact)
          }).success(function(response) {
            if (response.valid === "true" && response.send === "true") {
              $('#error').remove();
              return $('#emailForm').fadeOut(500, function() {
                $('#emailForm').remove();
                $('#success').fadeIn();
                $scope.contact = {};
              });
            }
          }).error(function() {
            alert('Brak połączenia z serwerem - proszę spróbować jeszcze raz');
          });
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=config.js.map

// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app.copyright', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/copyright', {
        templateUrl: 'views/copyright/index.html',
        controller: 'copyrightCtrl'
      });
    }
  ]).controller('copyrightCtrl', [
    '$scope', function($scope) {
      return $scope.currentYear = new Date().getFullYear();
    }
  ]);

}).call(this);

//# sourceMappingURL=config.js.map

// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app.frontPage', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/', {
        templateUrl: 'views/front-page/index.html',
        controller: 'frontPageCtrl'
      });
    }
  ]).controller('frontPageCtrl', [
    '$scope', function($scope) {
      return $scope.$on('$viewContentLoaded', function() {});
    }
  ]);

}).call(this);

//# sourceMappingURL=config.js.map

// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app.project', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/projects/:id', {
        templateUrl: 'views/project/index.html',
        controller: 'projectCtrl'
      });
    }
  ]).controller('projectCtrl', [
    '$scope', '$routeParams', '$http', '$location', function($scope, $routeParams, $http, $location) {
      return $http({
        method: 'GET',
        url: 'data/index.php?project=' + $routeParams.id
      }).success(function(response) {
        return $scope.selectedProject = response[0];
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=config.js.map

// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app.projects', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/projects', {
        templateUrl: 'views/projects/index.html',
        controller: 'projectsCtrl'
      });
    }
  ]).controller('projectsCtrl', [
    '$scope', '$http', '$location', function($scope, $http, $location) {
      return $http({
        method: 'GET',
        url: 'data/index.php?projects'
      }).success(function(response) {
        return $scope.projects = response;
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=config.js.map

// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app.skills', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/skills', {
        templateUrl: 'views/skills/index.html',
        controller: 'skillsCtrl'
      });
    }
  ]).controller('skillsCtrl', [
    '$scope', '$http', function($scope, $http) {
      $http({
        url: 'data/index.php?skill-lists'
      }).success(function(response) {
        return $scope.skillsList = response;
      });
      return $http({
        url: 'data/index.php?skill-icons'
      }).success(function(response) {
        return $scope.skillsIcons = response;
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=config.js.map
