// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app', ['ngRoute', 'ngAnimate', 'ngSanitize', 'angular-perfect-scrollbar-2', 'app.frontPage', 'app.projects', 'app.project', 'app.skills', 'app.canDo', 'app.copyright', 'app.aboutMe', 'app.contact']).config([
    '$locationProvider', '$routeProvider', function($locationProvider, $routeProvider) {
      $locationProvider.hashPrefix('!');
      return $routeProvider.otherwise({
        redirectTo: '/'
      });
    }
  ]).factory('viewStg', function($location) {
    return {
      changeView: function(view) {
        return $location.path(view);
      },
      isActive: function(viewLocation) {
        return viewLocation === $location.path();
      }
    };
  }).run(function($rootScope, viewStg) {
    return $rootScope.view = viewStg;
  });

}).call(this);

//# sourceMappingURL=app.js.map
