// Generated by CoffeeScript 1.10.0
(function() {
  $(document).ready(function() {
    if (!Modernizr.flexbox) {
      $('body').prepend('<span class="box-info">Twoja przeglądarka nie posiada wsparcia dla <strong>flex</strong>, związku z tym strona nie będzie poprawnie wyświetlana! Proszę <a href="http://browsehappy.com/">zaktualizować swoją przeglądarkę</a> aby zwiększyć swoje wrażenia z przeglądania internetu. </span>');
    }
    if (!Modernizr.mediaqueries) {
      return $('body').prepend('<span class="box-info">Twoja przeglądarka nie posiada wsparcia dla <strong>mediaqueries</strong>, związku z tym strona nie będzie poprawnie wyświetlana! Proszę <a href="http://browsehappy.com/">zaktualizować swoją przeglądarkę</a> aby zwiększyć swoje wrażenia z przeglądania internetu. </span>');
    }
  });

  window.AudioPlayer = (function() {
    var audio;

    audio = document.createElement('audio');

    audio.setAttribute('loop', '');

    function AudioPlayer(container) {
      this.container = container;
      this.container.appendChild(audio);
    }

    AudioPlayer.prototype.play = function() {
      audio.play();
      return this.isPlay = true;
    };

    AudioPlayer.prototype.stop = function() {
      audio.pause();
      return this.isPlay = false;
    };

    AudioPlayer.prototype.isPlay = false;

    AudioPlayer.prototype.togglePlay = function() {
      if (this.isPlay) {
        return this.stop();
      } else {
        return this.play();
      }
    };

    AudioPlayer.prototype.isSetSource = function() {
      return audio.hasAttribute('src');
    };

    AudioPlayer.prototype.setSource = function(url) {
      audio.setAttribute('src', url);
      return audio.load();
    };

    return AudioPlayer;

  })();

  $.initAudioPlayer = function() {
    var audioPlay, audioPlayer;
    AudioPlayer.prototype.getNewAudioAndPlay = function() {
      return $.ajax({
        method: 'GET',
        url: 'audio/index.php?getRandomAudio',
        success: (function(_this) {
          return function(data) {
            _this.setSource(data);
            return _this.play();
          };
        })(this)
      });
    };
    audioPlayer = new AudioPlayer(document.getElementById('audio-player'));
    audioPlay = $('#audio-play');
    audioPlay.on('click', function() {
      if (!audioPlayer.isSetSource()) {
        audioPlayer.getNewAudioAndPlay();
        $(this).removeClass();
        return $(this).addClass('fa fa-pause');
      } else if (audioPlayer.togglePlay()) {
        $(this).removeClass();
        return $(this).addClass('fa fa-pause');
      } else {
        audioPlay.removeClass();
        return audioPlay.addClass('fa fa-play');
      }
    });
    return $('#audio-next').on('click', function() {
      audioPlayer.getNewAudioAndPlay();
      audioPlay.removeClass();
      return audioPlay.addClass('fa fa-pause');
    });
  };

}).call(this);

//# sourceMappingURL=plugins.js.map
