// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app.canDo', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/can-do', {
        templateUrl: 'views/can-do/index.html',
        controller: 'canDoCtrl'
      });
    }
  ]).controller('canDoCtrl', [
    '$scope', '$http', function($scope, $http) {
      return $http({
        method: 'GET',
        url: 'data/index.php?offers'
      }).success(function(response) {
        return $scope.offers = response;
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=config.js.map
