// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app.copyright', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/copyright', {
        templateUrl: 'views/copyright/index.html',
        controller: 'copyrightCtrl'
      });
    }
  ]).controller('copyrightCtrl', [
    '$scope', function($scope) {
      return $scope.currentYear = new Date().getFullYear();
    }
  ]);

}).call(this);

//# sourceMappingURL=config.js.map
